added icd 9 cm
tuva-health/docs pull request #117
Opened 2023-05-10 15:41 UTC by thutuva

Added icd 9 cm to csv file, to sidebar.js, and created a page for it that does not display the data dictionary and says it's too large.

I also changed all references in CSV file to 'CMS' to 'Centers for Medicare & Medicaid Services (CMS)'

2023-05-10 18:25 UTC, aneiderhiser requested changes
I reviewed including docs and test running the sql from quickstart in snowflake.  Everything looks good except for the one minor link issue i commented on.

2023-05-10 18:25 UTC, aneiderhiser commented on static/data/terminology.csv
> +Conditions and Procedures,ICD-9-CM,Centers for Medicare & Medicaid Services (CMS),10.01.2014, 05.10.2023,/terminology/conditions-and-procedures/icd-10-pcs
this link goes to the icd-10-pcs page -- it needs to be changed to go to the icd-9-cm page

2023-05-10 18:25 UTC, aneiderhiser commented on static/data/terminology.csv
> +Conditions and Procedures,ICD-9-CM,Centers for Medicare & Medicaid Services (CMS),10.01.2014, 05.10.2023,/terminology/conditions-and-procedures/icd-10-pcs
literally updating this /terminology/conditions-and-procedures/icd-10-pcs to /terminology/conditions-and-procedures/icd-9-cm should work i think

2023-05-11 13:53 UTC, thutuva commented on static/data/terminology.csv
> +Conditions and Procedures,ICD-9-CM,Centers for Medicare & Medicaid Services (CMS),10.01.2014, 05.10.2023,/terminology/conditions-and-procedures/icd-10-pcs
nice catch!  The text has been corrected to icd-9-cm.

2023-05-11 13:55 UTC, merged