draft add fhir preprocessing guide
tuva-health/docs pull request #235
Opened 2024-02-26 23:46 UTC by tuvaforrest

2024-02-28 18:19 UTC, aneiderhiser requested changes

2024-02-28 18:19 UTC, aneiderhiser commented on sidebars.js
> +        "guides/fhir-preprocessing",
Let's change the order of the guides so that they are alphabetical

2024-02-28 18:19 UTC, aneiderhiser commented on docs/guides/fhir-preprocessing.md
> +Fast Healthcare Interoperability Resources (FHIR) is a standard for health care data exchange.
healthcare spelled one word

2024-02-28 18:19 UTC, aneiderhiser commented on docs/guides/fhir-preprocessing.md
> +
Add a very simple Miro diagram that shows the data transformation steps
- Start: Raw FHIR as JSON
- FHIR Inferno (flattens JSON to CSVs)
- Load CSVs into Data Warehouse
- Transform CSVs into Tuva Input Layer
- Run Tuva
- End: Analytics-ready Data

2024-02-28 18:19 UTC, aneiderhiser commented on docs/guides/fhir-preprocessing.md
> +
In this section we want to not only describe fhir inferno but the other components used in FHIR PP, namely HG connector and Tuva repo.

2024-02-28 18:19 UTC, aneiderhiser commented on docs/guides/fhir-preprocessing.md
> +## Getting Started
This section describes FHIR Inferno - let's rename it FHIR Inferno.  We need subsequent sections for HG Connector and Tuva.

2024-02-28 18:19 UTC, aneiderhiser commented on docs/guides/fhir-preprocessing.md
> +</details>
We need 2 sections below this: one for HG connector and one for running Tuva.  These can be shorter.

2024-02-29 12:21 UTC, tuvaforrest commented on docs/guides/fhir-preprocessing.md
> +
lol, I wanted to know if chat friend could make something more interesting.  I think it'll still be a few years before they take over the world or our jobs.

![image](https://github.com/tuva-health/docs/assets/100245109/b157a8f6-c088-4917-b55d-e62251d0d44c)

2024-03-30 18:27 UTC, aneiderhiser approved these changes

2024-03-30 18:27 UTC, merged